language: ruby
rvm:
  - 2.2.3

script: ./_ci/build

cache:
  bundler: true
  directories:
    - node_modules

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    - /./
